# Configure wst= token for VIP downloads
# To find out the value, log in to webshare.cz in browser and inspect an API request
# This value is likely to change after every login in browser - update as needed
wst: AwqK3EwNjehJVgSk

# Recommended to turn on if you've configured VIP
# force_vip: true

# Change order or add other options to change sorting of search results
quality:
  - 1080p web-dl
  - 1080p webrip
  - 1080p bluray
  - 1080p
  - 720p web-dl
  - 720p webrip
  - 720p bluray
  - 720p
  - ""  # Match-all option -- recommnended to keep as last option

# Whitelist for allowed file extensions
types:
  - mkv
  - mp4
  - avi
  - m4v
  - webm
